# Generated by Django 5.1.2 on 2024-11-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empl', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_empl', models.CharField(max_length=100)),
                ('apellido_empl', models.CharField(max_length=100)),
                ('domicilio_empl', models.CharField(max_length=200)),
                ('telefono_empl', models.CharField(max_length=15)),
                ('correo_empl', models.EmailField(max_length=254)),
                ('rol_empl', models.CharField(choices=[('cajero', 'Cajero'), ('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('admin', 'Admin')], max_length=20)),
                ('fecha_nacimiento_emp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('hs_login', models.DateTimeField(auto_now_add=True)),
                ('dni_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleados')),
            ],
        ),
    ]
