# Generated by Django 5.1.2 on 2024-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='usuario',
            new_name='username',
        ),
    ]
