# Generated by Django 5.1.2 on 2024-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_contraseña_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
