# Generated by Django 5.1.2 on 2024-11-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='ultimo_acceso',
            new_name='last_login',
        ),
    ]
