# Generated by Django 5.1.2 on 2024-11-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_ultimo_acceso_login_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='dni_empleado',
            new_name='dni_empl',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='last_login',
            new_name='ultimo_acceso',
        ),
    ]
