# Generated by Django 5.1.2 on 2024-11-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_dni_empleado_login_dni_empl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='usuario',
        ),
    ]
