# Generated by Django 5.1.2 on 2024-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_password_login_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='rol_empl',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('gerente', 'Gerente'), ('admin', 'Admin')], max_length=20),
        ),
    ]
